from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, EmailStr, Field

# ----------------- Auth & Doctor Schemas -----------------

class DoctorBase(BaseModel):
    name: str = Field(..., min_length=1, max_length=120)
    email: EmailStr
    specialty: Optional[str] = "General Medicine"
    phone: Optional[str] = None
    hospital_name: Optional[str] = "FedMedX Healthcare System"

class DoctorCreate(DoctorBase):
    password: str = Field(..., min_length=6)

class DoctorLogin(BaseModel):
    email: EmailStr
    password: str

class DoctorOut(DoctorBase):
    doctor_id: int
    created_at: datetime

    class Config:
        from_attributes = True

class Token(BaseModel):
    access_token: str
    token_type: str = "bearer"
    doctor: DoctorOut

class TokenData(BaseModel):
    doctor_id: Optional[int] = None
    email: Optional[str] = None


# ----------------- Patient Schemas -----------------

class PatientBase(BaseModel):
    name: str = Field(..., min_length=1, max_length=120)
    phone: Optional[str] = None
    age: int = Field(..., ge=0, le=130)
    gender: str = Field(..., pattern="^(Male|Female|Other)$")
    diagnosis: str = Field(..., min_length=1)
    medical_history: Optional[str] = None
    current_treatment: Optional[str] = None
    current_medicines: Optional[str] = None
    doctor_notes: Optional[str] = None
    visit_date: str

class PatientCreate(PatientBase):
    patient_uid: Optional[str] = None  # Autogenerated if not provided

class PatientUpdate(BaseModel):
    name: Optional[str] = None
    phone: Optional[str] = None
    age: Optional[int] = None
    gender: Optional[str] = None
    diagnosis: Optional[str] = None
    medical_history: Optional[str] = None
    current_treatment: Optional[str] = None
    current_medicines: Optional[str] = None
    doctor_notes: Optional[str] = None
    visit_date: Optional[str] = None


# ----------------- Report Schemas -----------------

class ReportOut(BaseModel):
    report_id: int
    patient_id: int
    report_type: str
    file_name: str
    file_type: str
    file_size: int
    google_drive_file_id: Optional[str] = None
    storage_provider: str
    is_sensitive: bool
    uploaded_by: int
    uploaded_at: datetime

    class Config:
        from_attributes = True

class PatientOut(PatientBase):
    patient_id: int
    patient_uid: str
    doctor_id: int
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True

class PatientDetailOut(PatientOut):
    reports: List[ReportOut] = []

    class Config:
        from_attributes = True


# ----------------- USB Security Schemas -----------------

class USBVerificationRequest(BaseModel):
    token: str

class USBKeyGenerateResponse(BaseModel):
    key_token: str
    label: str
    created_at: datetime
    instruction: str
    recommended_filename: str

class USBKeyOut(BaseModel):
    id: int
    label: str
    is_active: bool
    created_at: datetime
    last_used_at: Optional[datetime] = None

    class Config:
        from_attributes = True


# ----------------- Audit Log Schemas -----------------

class AuditLogOut(BaseModel):
    id: int
    doctor_email: Optional[str] = None
    action: str
    target_type: Optional[str] = None
    target_id: Optional[str] = None
    details: Optional[str] = None
    ip_address: Optional[str] = None
    timestamp: datetime

    class Config:
        from_attributes = True


# ----------------- Dashboard Stats -----------------

class DashboardStats(BaseModel):
    total_patients: int
    total_reports: int
    recent_visits_count: int
    sensitive_reports_count: int
    storage_provider: str
    google_drive_connected: bool
    usb_security_enabled: bool
